export const SET_BANNER_LIST = 'SET_BANNER_LIST';
export const SET_RECOMMEND_LIST = 'SET_RECOMMEND_LIST';
export const SET_NEW_SONG_LIST = 'SET_NEW_SONG_LIST';
export const SET_HAS_PLAYED = 'SET_HAS_PLAYED';
export const SET_FULL_SCRING_PLAYING = 'SET_FULL_SCRING_PLAYING';
export const SET_PLAY_LIST_DETAIL = 'SET_PLAY_LIST_DETAIL';
export const SET_PLAY_SONG_LIST = 'SET_PLAY_SONG_LIST';
export const SET_PLAY_MODEL = 'SET_PLAY_MODEL';
export const SET_PLAY_INDEX = 'SET_PLAY_INDEX';
export const SET_PLAY_ID = 'SET_PLAY_ID';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_CURRENT_SONG_URL = 'SET_CURRENT_SONG_URL';
export const SET_TOP_SINGER_LIST = 'SET_TOP_SINGER_LIST';
export const SET_SINGER_INFO = 'SET_SINGER_INFO';
export const SET_SINGER_SONG_LIST = 'SET_SINGER_SONG_LIST';
export const SET_TOAST_STATE = 'SET_TOAST_STATE';
export const SET_SONG_URL_CAN_PLAY = 'SET_SONG_URL_CAN_PLAY';
export const SET_OFFICIAL_RANK_LIST = 'SET_OFFICIAL_RANK_LIST';
export const SET_OTHER_RANK_LIST = 'SET_OTHER_RANK_LIST';
export const SET_PLAY_LIST_INFO = 'SET_PLAY_LIST_INFO';




